
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/hashicorp/go-plugin", "github.com/hashicorp/go-hclog", "golang.org/x/net*"]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.8.26"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.9"

[[constraint]]
  name = "github.com/coreos/pkg"
  version = "3.0.0"

[[constraint]]
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.4.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.4.0"
