image:
  repository: serverless/event-gateway
  tag: 0.9.0
  pullPolicy: IfNotPresent
replicaCount: 3
service:
  type: LoadBalancer
  config:
    port: 4001
  events:
    port: 4000
  annotations: []
resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 200m
   memory: 256Mi
command: ["-log-level=debug"]
etcd_cluster_name: eg-etcd-cluster
etcd_cluster_port: 2379
